### ISSUE TITLE
tty scroll crashes kernel

### ISSUE THREAD

**Issue by rainerrudigier** [ulmer-a/ulmix#14]
when screen wants to scroll it crashes the kernel with:

00000000000i[      ] installing x module as the Bochs GUI
00000000000i[      ] using log file log
Next at t=0
(0) [0x0000fffffff0] f000:fff0 (no symbol): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:1> c
(0).[29806236] [0x00000010244c] 0008:0010244c (               memmove+2c): mov byte ptr ds:[ebx+edx], al ; 880413
Next at t=29806237
(0) [0x0000fffffff0] f000:fff0 (no symbol): jmpf 0xf000:e05b          ; ea5be000f0
<bochs:2>

removing the memmove of the scroll function keeps the kernel running ..

static void scroll(struct tty_struct *tty)
{
//    int src = COLUMNS * 2;
   int len = COLUMNS * (LINES - 2) * 2;
//    memmove(tty->vmem, (void*)(tty->vmem + src), len);

   for (int i = len; i < COLUMNS*LINES*2; i += 2)
   {
       tty->vmem[i] = 0;
       tty->vmem[i+1] = tty->color;
   }

//    tty->pos_y = LINES - 1;
   tty->pos_y = 0;
   set_cursor(tty);
}

**Comment by ulmer-a** [comment]
Should be just memcpy() and not memmove().
Now fixed.
